version: '3.1'

services:

  ##################
  # Node Container
  ##################
  server:
    image: demonicmushy/chatbotplatform:server
    environment:
      - MICL_ENDPOINT=http://13.76.152.232:8081
      - FLASK_ENDPOINT=http://api:5000
      - SPEECH_API=ws://40.90.170.182:8001/client/ws/speech
      - SPEECH_HTTP_API=http://40.90.170.182:8001/client/dynamic/recognize
      - SPEECH_HTTP_AUTH=https://api.speechlab.sg/auth
      - DIALOGFLOW_KEYFILENAME_COVID19=/run/secrets/dialog_covid19
      - DIALOGFLOW_KEYFILENAME_BABYBONUS=/run/secrets/dialog_babybonus
      - RAJAT_ENDPOINT_BABYBONUS=http://13.76.152.232:1995
      - RAJAT_ENDPOINT_COVID19=http://13.76.152.232:2995
      - RUSHI_ENDPOINT_BABYBONUS=http://13.76.152.232:1996
      - RUSHI_ENDPOINT_COVID19=http://13.76.152.232:1997
      - AISG_CREDENTIALS=/run/secrets/aisg_credentials
    ports:
      # HTTPS server port : server listening port
      - '3002:3001'
    deploy:
      replicas: 1
    secrets:
      - dialog_babybonus
      - dialog_covid19
      - aisg_credentials

  ##################
  # Flask Container
  ##################
  api:
    image: demonicmushy/chatbotplatform:api
    environment:
      - PORT=5000
    deploy:
      replicas: 1

  ##################
  # Client Container
  ##################
  client:
    image: demonicmushy/chatbotplatform:client
    ports:
      # HTTPS client port : client listening port
      - '3003:80'
    deploy:
      replicas: 1

secrets:
  dialog_babybonus:
    external: true
  dialog_covid19:
    external: true
  aisg_credentials:
    external: true