version: '3'

services:

  ##################
  # Node Container
  ##################
  server:
    image: demonicmushy/chatbotplatform:server
    build:
      context: ../backend
    environment:
      - MICL_ENDPOINT=http://13.76.152.232:8081
      - FLASK_ENDPOINT=http://api:5000
      - AISG_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkNzBjYmE2ZjBkNmUzMDAxYzFlNjViOSIsImlhdCI6MTU4OTc3OTcxMiwiZXhwIjoxNTkyMzcxNzEyfQ.eodSwv4w_yTfl6AhbwKC-Or_YygD2bzSP-HrU04IFWc
      - SPEECH_API=ws://40.90.170.182:8001/client/ws/speech
      - SPEECH_HTTP_API=http://40.90.170.182:8001/client/dynamic/recognize
      - DIALOGFLOW_PROJECT_ID_COVID19=covid19chatbot-stsokd
      - DIALOGFLOW_PROJECT_ID_BABYBONUS=chatbotframework-qmylfo
      - DIALOGFLOW_KEYFILENAME_COVID19=covid19chatbot-stsokd-fe15dee83215.json
      - DIALOGFLOW_KEYFILENAME_BABYBONUS=chatbotframework-qmylfo-db2ef824f8e0.json
      - RAJAT_ENDPOINT_BABYBONUS=http://13.76.152.232:1995
      - RAJAT_ENDPOINT_COVID19=http://13.76.152.232:2995
    ports:
      - '3001:3001'
    deploy:
      replicas: 1

#    volumes:
#      - ../online_asr_backend/routes:/srv/app/server/routes
#    command: npm run dev

  ##################
  # Flask Container
  ##################
  api:
    image: demonicmushy/chatbotplatform:api
    build: ../comparison
    environment:
      - PORT=5000
    deploy:
      replicas: 1

   # volumes:
   #   - ../production:/api
   # command: python flaskApp.py
   # environment:
   #   - FLASK_ENV=development
   #   - FLASK_APP=flaskApp.py
   #   - FLASK_DEBUG=1

  ##################
  # Client Container
  ##################
  client:
    image: demonicmushy/chatbotplatform:client
    build:
      context: ../frontend
      args:
        # need to specify here because it will be complied into image
        - REACT_APP_API=https://chatbot.speechlab.sg:3001
    ports:
      - '3000:80'
    deploy:
      replicas: 1

#    volumes:
#      - ../dialogflowapp/src:/srv/app/client/src
#      - ../dialogflowapp/public:/srv/app/client/public
#    command: npm run start
